import Head from "next/head";
import styles from "@kenk2/styles/Home.module.css";
import { Diagnostic, Intro } from "@kenk2/components";
import { useQuestions } from "@kenk2/hooks";
import { DiagnosticResponses } from "@kenk2/types";
import { useState } from "react";
import { Backdrop } from "@mui/material";

export default function Home() {
  const { data, isLoading: isLoadingDiagnostic } = useQuestions();
  const [started, setStarted] = useState<boolean>(false);

  const handleSubmit = (results: DiagnosticResponses) => {};

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {started && data?.data ? (
          <Diagnostic diagnostic={data?.data} onSubmit={handleSubmit} />
        ) : (
          <Intro
            loading={isLoadingDiagnostic}
            onStart={() => setStarted(true)}
            diagnostic={data?.data}
          />
        )}
      </main>
    </>
  );
}
