import Head from "next/head";
import styles from "@kenk2/styles/Home.module.css";
import { Diagnostic } from "@kenk2/components";
import { useQuestions } from "@kenk2/hooks";

export default function Home() {
  const { data } = useQuestions();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {data?.data ? <Diagnostic diagnostic={data?.data} /> : null}
      </main>
    </>
  );
}
